In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("iris.csv")

In [3]:
df.head

<bound method NDFrame.head of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [4]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [5]:
df.shape

(150, 5)

In [6]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [7]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [8]:
df.isnull()

     sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [9]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [16]:
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0
5           5.4          3.9           1.7          0.4        0
6           4.6          3.4           1.4          0.3        0
7           5.0          3.4           1.5          0.2        0
8           4.4          2.9           1.4          0.2        0
9           4.9          3.1           1.5          0.1        0

In [ ]:
df['species']=df['species'].map({'setosa':1,'virginica':2})

In [12]:
df

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2      1.0
1             4.9          3.0           1.4          0.2      1.0
2             4.7          3.2           1.3          0.2      1.0
3             4.6          3.1           1.5          0.2      1.0
4             5.0          3.6           1.4          0.2      1.0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3      2.0
146           6.3          2.5           5.0          1.9      2.0
147           6.5          3.0           5.2          2.0      2.0
148           6.2          3.4           5.4          2.3      2.0
149           5.9          3.0           5.1          1.8      2.0

[150 rows x 5 columns]

In [13]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [21]:
df[df['species']==0]

    sepal_length  sepal_width  petal_length  petal_width  species
0            5.1          3.5           1.4          0.2        0
1            4.9          3.0           1.4          0.2        0
2            4.7          3.2           1.3          0.2        0
3            4.6          3.1           1.5          0.2        0
4            5.0          3.6           1.4          0.2        0
5            5.4          3.9           1.7          0.4        0
6            4.6          3.4           1.4          0.3        0
7            5.0          3.4           1.5          0.2        0
8            4.4          2.9           1.4          0.2        0
9            4.9          3.1           1.5          0.1        0
10           5.4          3.7           1.5          0.2        0
11           4.8          3.4           1.6          0.2        0
12           4.8          3.0           1.4          0.1        0
13           4.3          3.0           1.1          0.1        0
14           5.8          4.0           1.2          0.2        0
15           5.7          4.4           1.5          0.4        0
16           5.4          3.9           1.3          0.4        0
17           5.1          3.5           1.4          0.3        0
18           5.7          3.8           1.7          0.3        0
19           5.1          3.8           1.5          0.3        0
20           5.4          3.4           1.7          0.2        0
21           5.1          3.7           1.5          0.4        0
22           4.6          3.6           1.0          0.2        0
23           5.1          3.3           1.7          0.5        0
24           4.8          3.4           1.9          0.2        0
25           5.0          3.0           1.6          0.2        0
26           5.0          3.4           1.6          0.4        0
27           5.2          3.5           1.5          0.2        0
28           5.2          3.4           1.4          0.2        0
29           4.7          3.2           1.6          0.2        0
30           4.8          3.1           1.6          0.2        0
31           5.4          3.4           1.5          0.4        0
32           5.2          4.1           1.5          0.1        0
33           5.5          4.2           1.4          0.2        0
34           4.9          3.1           1.5          0.1        0
35           5.0          3.2           1.2          0.2        0
36           5.5          3.5           1.3          0.2        0
37           4.9          3.1           1.5          0.1        0
38           4.4          3.0           1.3          0.2        0
39           5.1          3.4           1.5          0.2        0
40           5.0          3.5           1.3          0.3        0
41           4.5          2.3           1.3          0.3        0
42           4.4          3.2           1.3          0.2        0
43           5.0          3.5           1.6          0.6        0
44           5.1          3.8           1.9          0.4        0
45           4.8          3.0           1.4          0.3        0
46           5.1          3.8           1.6          0.2        0
47           4.6          3.2           1.4          0.2        0
48           5.3          3.7           1.5          0.2        0
49           5.0          3.3           1.4          0.2        0

In [14]:
df.columns.values

array(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'], dtype=object)

In [15]:
df.describe(include='all')

       sepal_length  sepal_width  petal_length  petal_width     species
count    150.000000   150.000000    150.000000   150.000000  100.000000
mean       5.843333     3.054000      3.758667     1.198667    1.500000
std        0.828066     0.433594      1.764420     0.763161    0.502519
min        4.300000     2.000000      1.000000     0.100000    1.000000
25%        5.100000     2.800000      1.600000     0.300000    1.000000
50%        5.800000     3.000000      4.350000     1.300000    1.500000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

In [16]:
df = pd.get_dummies(df,columns=['species'])

In [17]:
df

,sepal_length,sepal_width,petal_length,petal_width,species_1.0,species_2.0
0,5.1,3.5,1.4,0.2,True,False
1,4.9,3.0,1.4,0.2,True,False
2,4.7,3.2,1.3,0.2,True,False
3,4.6,3.1,1.5,0.2,True,False
4,5.0,3.6,1.4,0.2,True,False
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,False,True
146,6.3,2.5,5.0,1.9,False,True
147,6.5,3.0,5.2,2.0,False,True
148,6.2,3.4,5.4,2.3,False,True
149,5.9,3.0,5.1,1.8,False,True